### ISSUE TITLE
excel data pulling

### ISSUE THREAD

**Issue by htc121** [sarveshgawand/Calculating-Implied-Option-Volatality-for-NIFTY-OPTIONS#1]
How do you pull data in the format that you have shown in the attached spreadsheet.

**Comment by sarveshgawand** [comment]
Hi,

I have pulled it using extract data from web functionality of Excel it also
has a feature to continuously update the table using a prespecified time.
Another technique which you can use is by parsing the html code for the
webpage to the BeautifulSoup library from bs4 of Python. It would require
you to identify the class where the values get updated.
Hope this helps.

Regards,
Sarvesh Gawand

**Comment by htc121** [comment]
Got it.
